### ISSUE TITLE
Python 3.14 Support

### ISSUE THREAD

**Issue by guilhermeivo** [arkanjo-tool/arkanjo#7]
The `gensim` package currently fails to install and run on Python 3.14 due to Cython compilation errors.

It works fine on Python 3.8--3.11, but newer versions are not compatible.
